CREATE TABLE USUARIO(
	username VARCHAR(20) PRIMARY KEY,
	password VARCHAR(20) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE EVENTO(
	eventoid INTEGER PRIMARY KEY,
	nombre VARCHAR(50),
	descripcion VARCHAR(200),
	fecha DATE NOT NULL,
	lugar VARCHAR(50) NOT NULL,
	capacidad INTEGER NOT NULL,
	afiche VARCHAR(200)
);	

CREATE TABLE ASISTE(
	participante VARCHAR(20) REFERENCES USUARIO(username),
	evento INTEGER REFERENCES EVENTO(eventoid),
	credencial VARCHAR(200),
	certificado VARCHAR(200),
	asistio BOOLEAN NOT NULL DEFAULT FALSE
);